name: Latest blog post workflow
on:
  schedule:
    - cron: '0 0 * * *' # Run the workflow every day at midnight (UTC) 
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Take my Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@jp-sec"
          max_post_count: 3 # Display only the latest 3 posts
