name: Latest blog post workflow

on:
  push:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@josselin_poupeney"

      - name: Limit to latest 3 blog posts
        run: |
          # Use awk to extract the latest 3 blog posts
          awk '/<!-- BLOG-POST-LIST:START -->/,/<!-- BLOG-POST-LIST:END -->/{if (NR >= 3) exit} {print}' blog_posts.md > latest_posts.md
          mv latest_posts.md blog_posts.md

      - name: Update README with latest posts
        run: |
          # Update the README with the latest blog posts
          sed -i '/<!-- BLOG-POST-LIST:START -->/,/<!-- BLOG-POST-LIST:END -->/d' README.md
          sed -i '/<h3 align="left">Connect with me:/,$d' README.md  # Remove the "Connect with me" section
          cat blog_posts.md >> README.md
